# NOTE: if you change this file,
# ALSO change the setup.py file
name: metapool
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  # base requirements
  - biom-format
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - python=3.9
  - seaborn[version='>=0.13.2']
  - seqtk[version='>=1.4']
  - scikit-learn
  # testing requirements
  - flake8
  - nose
  - papermill
  - pep8
  # notebook requirements
  - jupyter
  - notebook
  - watermark
  - pip:
      # base requirements
      - sample-sheet
      # coverage requirements
      - coverage
      - coveralls
      # notebook requirements
      - ipykernel
