name: Core Metapool CI Workflow
on:
  workflow_call:

jobs:
  # name of job
  build:
    # The type of runner that the job will run on (available options are window/macOS/linux)
    runs-on: ubuntu-latest
    # we can add more versions of node.js in the future
    strategy:
      matrix:
        python-version: ['3.9']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # first grab branch from github
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0


      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: tester
          python-version: ${{ matrix.python-version }}
          # channels: anaconda, conda-forge, bioconda, defaults
          auto-update-conda: true

      - name: Install metapool
        shell: bash -l {0}
        run: |
          conda env create --file environment.yml
          conda activate metapool
          pip install ".[all]"

      - name: Run tests and measure coverage
        shell: bash -l {0}
        run: |
          conda activate metapool
          nosetests --with-coverage --cover-inclusive --cover-erase --cover-package=metapool,notebooks
          # -i switch introduced to ignore errors when reading source files.
          # See: https://stackoverflow.com/questions/2386975/no-source-for-code-message-in-coverage-py
          coverage report -i

      - name: Python linter
        shell: bash -l {0}
        run: |
          conda activate metapool
          flake8 --exclude versioneer.py,metapool/_version.py .

      - name: Check deploy script syntax
        run: bash -n ./deploy.sh

      - name: Lint bash scripts with ShellCheck
        # Only check for (and thus fail on) on warnings or errors
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          ignore_paths: ./qiita-dev/test_data_studies/commands.sh

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Run tests and measure coverage

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
